"""
Unit tests for code generator.
"""

import unittest
import sys
import os
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from parsub.generator.code_generator import CodeGenerator


class TestCodeGenerator(unittest.TestCase):
    """Test cases for code generator."""

    def setUp(self):
        self.test_dir = "./test_output"
        self.generator = CodeGenerator(output_dir=self.test_dir)

    def tearDown(self):
        # Clean up test directory
        import shutil
        if os.path.exists(self.test_dir):
            shutil.rmtree(self.test_dir)

    def test_generator_initialization(self):
        """Test that generator initializes correctly."""
        self.assertIsInstance(self.generator, CodeGenerator)
        self.assertTrue(os.path.exists(self.test_dir))
        self.assertTrue(os.path.exists(os.path.join(self.test_dir, "plots")))
        self.assertTrue(os.path.exists(os.path.join(self.test_dir, "data")))

    def test_generate_header(self):
        """Test header generation."""
        header = self.generator._generate_header()
        self.assertIn("Generated by ParSub", header)
        self.assertIn('"""', header)

    def test_generate_imports(self):
        """Test imports generation."""
        imports = self.generator._generate_imports()
        self.assertIn("import numpy as np", imports)
        self.assertIn("import sympy as sp", imports)
        self.assertIn("import matplotlib.pyplot as plt", imports)

    def test_generate_helper_functions(self):
        """Test helper functions generation."""
        helpers = self.generator._generate_helper_functions()
        self.assertIn("def lambdify_expr", helpers)
        self.assertIn("def save_plot", helpers)
        self.assertIn("def save_data", helpers)

    def test_generate_evaluation_code_block(self):
        """Test evaluation code block generation."""
        task = {
            'expression': 'x**2',
            'variables': ['x'],
            'goal_type': 'evaluate',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 100,
                'ranges': {'x': (-5, 5)}
            },
            'expected_output_type': 'function'
        }

        code = self.generator._generate_evaluation_code_block(
            task['expression'],
            task['variables'],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: Evaluate expression", code)
        self.assertIn("lambdify_expr", code)
        self.assertIn("np.linspace", code)
        self.assertIn("save_data", code)

    def test_generate_1d_plot_code_block(self):
        """Test 1D plot code block generation."""
        task = {
            'expression': 'sin(x)',
            'variables': ['x'],
            'goal_type': 'plot',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 200,
                'ranges': {'x': (0, 2*3.14159)}
            },
            'expected_output_type': 'array'
        }

        code = self.generator._generate_1d_plot_code(
            task['expression'],
            task['variables'][0],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: 1D Plot", code)
        self.assertIn("np.linspace", code)
        self.assertIn("lambdify_expr", code)
        self.assertIn("plt.subplots", code)
        self.assertIn("save_plot", code)
        self.assertIn("save_data", code)

    def test_generate_2d_plot_code_block(self):
        """Test 2D plot code block generation."""
        task = {
            'expression': 'x**2 + y**2',
            'variables': ['x', 'y'],
            'goal_type': 'plot',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 400,  # sqrt(400)=20 for each dimension
                'ranges': {'x': (-5, 5), 'y': (-5, 5)}
            },
            'expected_output_type': 'array'
        }

        code = self.generator._generate_2d_plot_code(
            task['expression'],
            task['variables'][0],
            task['variables'][1],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: 2D Surface Plot", code)
        self.assertIn("np.meshgrid", code)
        self.assertIn("lambdify_expr", code)
        self.assertIn("plot_surface", code)
        self.assertIn("save_plot", code)
        self.assertIn("save_data", code)

    def test_generate_solve_code_block(self):
        """Test solve code block generation."""
        task = {
            'expression': 'x**2 - 4',
            'variables': ['x'],
            'goal_type': 'solve',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 100,
                'ranges': {'x': (-5, 5)}
            },
            'expected_output_type': 'function'
        }

        code = self.generator._generate_solve_code_block(
            task['expression'],
            task['variables'],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: Solve equation", code)
        self.assertIn("sp.solve", code)
        self.assertIn("save_data", code)

    def test_generate_optimize_code_block(self):
        """Test optimize code block generation."""
        task = {
            'expression': '(x-2)**2 + 3',
            'variables': ['x'],
            'goal_type': 'optimize',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 100,
                'ranges': {'x': (-5, 5)}
            },
            'expected_output_type': 'function'
        }

        code = self.generator._generate_optimize_code_block(
            task['expression'],
            task['variables'],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: Optimization", code)
        self.assertIn("optimize.minimize", code)
        self.assertIn("save_data", code)

    def test_generate_integrate_code_block(self):
        """Test integrate code block generation."""
        task = {
            'expression': 'x**2',
            'variables': ['x'],
            'goal_type': 'integrate',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 50,
                'ranges': {'x': (0, 2)}
            },
            'expected_output_type': 'function'
        }

        code = self.generator._generate_integrate_code_block(
            task['expression'],
            task['variables'],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: Integration", code)
        self.assertIn("sp.integrate", code)
        self.assertIn("save_data", code)

    def test_generate_differentiate_code_block(self):
        """Test differentiate code block generation."""
        task = {
            'expression': 'x**2',
            'variables': ['x'],
            'goal_type': 'differentiate',
            'parameters': {},
            'suggested_sampling': {
                'method': 'uniform',
                'points': 50,
                'ranges': {'x': (-2, 2)}
            },
            'expected_output_type': 'function'
        }

        code = self.generator._generate_differentiate_code_block(
            task['expression'],
            task['variables'],
            task['suggested_sampling'],
            1
        )

        self.assertIn("Task 1: Differentiation", code)
        self.assertIn("sp.diff", code)
        self.assertIn("save_data", code)

    def test_generate_complete_code(self):
        """Test complete code generation."""
        tasks = [
            {
                'expression': 'x**2',
                'variables': ['x'],
                'goal_type': 'evaluate',
                'parameters': {},
                'suggested_sampling': {
                    'method': 'uniform',
                    'points': 50,
                    'ranges': {'x': (-5, 5)}
                },
                'expected_output_type': 'function'
            }
        ]

        code = self.generator.generate_evaluation_code(tasks)

        self.assertIn('"""Generated by ParSub', code)
        self.assertIn("import numpy as np", code)
        self.assertIn("def lambdify_expr", code)
        self.assertIn("Task 1: Evaluate expression", code)
        self.assertIn('if __name__ == "__main__":', code)

    def test_save_code(self):
        """Test saving code to file."""
        tasks = [
            {
                'expression': 'x**2',
                'variables': ['x'],
                'goal_type': 'evaluate',
                'parameters': {},
                'suggested_sampling': {
                    'method': 'uniform',
                    'points': 50,
                    'ranges': {'x': (-5, 5)}
                },
                'expected_output_type': 'function'
            }
        ]

        code = self.generator.generate_evaluation_code(tasks)
        filepath = self.generator.save_code(code, "test_code.py")

        self.assertTrue(os.path.exists(filepath))
        self.assertTrue(filepath.endswith("test_code.py"))

        # Check that file contains expected content
        with open(filepath, 'r') as f:
            content = f.read()
        self.assertIn("Generated by ParSub", content)
        self.assertIn("x**2", content)


if __name__ == '__main__':
    unittest.main()