"""
Unit tests for the code generator and the runtime helpers it embeds.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

import numpy as np
import sympy as sp

from parsub.analyzer.expression_analyzer import analyze_expressions
from parsub.generator import runtime
from parsub.generator.code_generator import CodeGenerator, generate_code_from_tasks


def make_task(expression, goal, variables, ranges, **extra):
    task = {
        "expression": expression,
        "srepr": sp.srepr(sp.sympify(expression)),
        "variables": variables,
        "goal_type": goal,
        "parameters": {},
        "suggested_sampling": {"method": "uniform", "points": 50, "ranges": ranges},
        "expected_output_type": "function",
        "independent_variables": variables[:1],
        "fixed_parameters": {},
    }
    task.update(extra)
    return task


def run_script(path, output_dir):
    return subprocess.run(
        [sys.executable, path, "--output-dir", output_dir],
        capture_output=True,
        text=True,
        timeout=300,
    )


class TestCodeGenerator(unittest.TestCase):
    """Test cases for code generator."""

    def setUp(self):
        self.test_dir = tempfile.mkdtemp(prefix="parsub_test_")
        self.generator = CodeGenerator(output_dir=self.test_dir)

    def tearDown(self):
        shutil.rmtree(self.test_dir, ignore_errors=True)

    def test_generator_initialization(self):
        self.assertTrue(os.path.isdir(os.path.join(self.test_dir, "plots")))
        self.assertTrue(os.path.isdir(os.path.join(self.test_dir, "data")))

    def test_generate_header(self):
        header = self.generator._generate_header("paper.tex", 3)
        self.assertTrue(header.startswith('"""Generated by ParSub'))
        self.assertIn("Source: paper.tex", header)

    def test_header_is_injection_safe(self):
        code = self.generator.generate_evaluation_code([], source_name='evil"""\nimport os\n"""')
        compile(code, "generated.py", "exec")
        self.assertNotIn("\nimport os\n\"\"\"", code)

    def test_generate_helper_functions(self):
        helpers = self.generator._generate_helper_functions()
        for name in ("def lambdify_expr", "def save_plot", "def save_data", "def run_tasks"):
            self.assertIn(name, helpers)

    def test_generated_code_compiles_for_every_goal(self):
        tasks = [
            make_task("x**2", "evaluate", ["x"], {"x": (-5, 5)}),
            make_task("sin(x)", "plot", ["x"], {"x": (0, 6.28)}),
            make_task("x**2 + y**2", "plot", ["x", "y"], {"x": (-5, 5), "y": (-5, 5)},
                      independent_variables=["x", "y"]),
            make_task("x**2 - 4", "solve", ["x"], {"x": (-5, 5)}, options={"solve_for": "x"}),
            make_task("(x-2)**2 + 3", "optimize", ["x"], {"x": (-5, 5)}, options={"direction": "minimize"}),
            make_task("x**2", "integrate", ["x"], {"x": (0, 2)}),
            make_task("x**3", "differentiate", ["x"], {"x": (-2, 2)}),
            make_task("exp(x)", "series", ["x"], {"x": (-1, 1)}),
        ]
        code = self.generator.generate_evaluation_code(tasks)
        compile(code, "generated.py", "exec")
        for call in ("evaluate_task(", "plot_task(", "solve_task(", "optimize_task(", "integrate_task(",
                     "differentiate_task(", "series_task("):
            self.assertIn(call, code)
        self.assertIn('if __name__ == "__main__":', code)

    def test_generated_script_runs_and_writes_outputs(self):
        tasks = [
            make_task("x**2", "evaluate", ["x"], {"x": (-5, 5)}),
            make_task("x**2 + y**2", "plot", ["x", "y"], {"x": (-5, 5), "y": (-5, 5)},
                      independent_variables=["x", "y"]),
            make_task("x**2 - 4", "solve", ["x"], {"x": (-5, 5)}, options={"solve_for": "x"}),
            make_task("(x-2)**2 + 3", "optimize", ["x"], {"x": (-5, 5)}, options={"direction": "minimize"}),
            make_task("x**2", "integrate", ["x"], {"x": (0, 2)}),
            make_task("x**3", "differentiate", ["x"], {"x": (-2, 2)}),
            make_task("exp(x)", "series", ["x"], {"x": (-1, 1)}),
        ]
        path = generate_code_from_tasks(tasks, self.test_dir, source_name="unit test")
        result = run_script(path, self.test_dir)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

        data = os.path.join(self.test_dir, "data")
        with open(os.path.join(data, "summary.json")) as handle:
            summary = json.load(handle)
        self.assertEqual(summary["failed"], 0)
        self.assertEqual(summary["succeeded"], 7)

        with open(os.path.join(data, "task_3_solutions.json")) as handle:
            solutions = json.load(handle)
        self.assertEqual(sorted(solutions["solutions_at_fixed_parameters"]), [-2.0, 2.0])
        self.assertEqual(len(solutions["numeric_roots_in_range"]), 2)

        with open(os.path.join(data, "task_4_optimization.json")) as handle:
            optimum = json.load(handle)
        self.assertAlmostEqual(optimum["minimum"]["point"]["x"], 2.0, places=4)
        self.assertAlmostEqual(optimum["minimum"]["value"], 3.0, places=6)

        with open(os.path.join(data, "task_5_integration.json")) as handle:
            integral = json.load(handle)
        self.assertAlmostEqual(integral["definite_integral"]["value"], 8 / 3, places=8)
        self.assertEqual(integral["antiderivative"], "x**3/3")

        with open(os.path.join(data, "task_6_differentiation.json")) as handle:
            self.assertEqual(json.load(handle)["partial_derivatives"], {"x": "3*x**2"})

        plots = os.listdir(os.path.join(self.test_dir, "plots"))
        self.assertIn("task_2_surface_plot.png", plots)
        self.assertIn("task_1_evaluation.png", plots)

    def test_failing_task_does_not_stop_others(self):
        tasks = [
            make_task("x**2", "evaluate", ["x"], {"x": (-1, 1)}),
            make_task("x", "series", ["x"], {"x": (-1, 1)}),
        ]
        code = self.generator.generate_evaluation_code(tasks)
        code = code.replace("def task_2(ctx):", "def task_2(ctx):\n    raise ValueError('boom')")
        path = self.generator.save_code(code)
        result = run_script(path, self.test_dir)
        self.assertEqual(result.returncode, 1)
        with open(os.path.join(self.test_dir, "data", "summary.json")) as handle:
            summary = json.load(handle)
        self.assertEqual([t["status"] for t in summary["tasks"]], ["ok", "failed"])
        self.assertIn("boom", summary["tasks"][1]["error"])

    def test_tasks_from_analyzer(self):
        expressions = [{"sympy_expr": sp.Eq(sp.Symbol("E"), sp.Symbol("m") * sp.Symbol("c") ** 2)}]
        tasks = analyze_expressions(expressions)
        code = self.generator.generate_evaluation_code(tasks)
        # E is a symbol here, not Euler's number: the expression is rebuilt from srepr
        self.assertIn("Symbol('c')", code)
        compile(code, "generated.py", "exec")

    def test_save_code(self):
        code = self.generator.generate_evaluation_code([make_task("x**2", "evaluate", ["x"], {"x": (-5, 5)})])
        filepath = self.generator.save_code(code, "test_code.py")
        self.assertTrue(os.path.exists(filepath))
        with open(filepath) as handle:
            content = handle.read()
        self.assertIn("Generated by ParSub", content)
        self.assertIn("Symbol('x')", content)


class TestRuntime(unittest.TestCase):
    """Test cases for the runtime helpers embedded in generated scripts."""

    def setUp(self):
        self.test_dir = tempfile.mkdtemp(prefix="parsub_runtime_")
        self.ctx = runtime.OutputContext(self.test_dir)

    def tearDown(self):
        shutil.rmtree(self.test_dir, ignore_errors=True)

    def test_lambdify_vectorised(self):
        f = runtime.lambdify_expr(sp.sympify("a*x**2"), ["x"], {"a": 2})
        self.assertFalse(f.pointwise)
        np.testing.assert_allclose(f(np.array([1.0, 2.0])), [2.0, 8.0])

    def test_lambdify_constant_broadcasts(self):
        f = runtime.lambdify_expr(sp.Integer(3), ["x"])
        np.testing.assert_allclose(f(np.zeros(4)), [3, 3, 3, 3])

    def test_lambdify_pointwise_for_integrals(self):
        t, z = sp.symbols("t z")
        f = runtime.lambdify_expr(sp.Integral(t ** (z - 1) * sp.exp(-t), (t, 0, sp.oo)), ["z"])
        self.assertTrue(f.pointwise)
        np.testing.assert_allclose(f(np.array([1.0, 3.0, 5.0])), [1.0, 2.0, 24.0], rtol=1e-8)

    def test_complex_values_become_nan(self):
        f = runtime.lambdify_expr(sp.sqrt(sp.Symbol("x")), ["x"])
        values = f(np.array([-1.0, 4.0]))
        self.assertTrue(np.isnan(values[0]))
        self.assertEqual(values[1], 2.0)

    def test_save_data_formats(self):
        for name in ("a.csv", "a.tsv", "a.xlsx", "a.json"):
            path = runtime.save_data({"x": np.arange(3), "y": np.arange(3) ** 2}, name, ctx=self.ctx)
            self.assertTrue(os.path.exists(path))
        path = runtime.save_data({"value": float("nan"), "items": [1, 2]}, "b.json", ctx=self.ctx)
        with open(path) as handle:
            self.assertEqual(json.load(handle), {"value": None, "items": [1, 2]})

    def test_verify_task(self):
        x = sp.Symbol("x")
        summary = runtime.verify_task(self.ctx, 1, sp.sin(x) ** 2 + sp.cos(x) ** 2, sp.Integer(1), ["x"],
                                      ranges={"x": (-3, 3)})
        self.assertTrue(summary["identity_holds_numerically"])
        summary = runtime.verify_task(self.ctx, 2, sp.sin(x), sp.cos(x), ["x"], ranges={"x": (-3, 3)})
        self.assertFalse(summary["identity_holds_numerically"])

    @unittest.skipUnless(hasattr(__import__("signal"), "SIGALRM"), "time limits need SIGALRM")
    def test_time_limit(self):
        with self.assertRaises(runtime.TaskTimeout):
            with runtime.time_limit(0.2):
                while True:
                    pass
        ok, message = runtime.attempt(lambda: 1 / 0)
        self.assertFalse(ok)
        self.assertIn("ZeroDivisionError", message)


if __name__ == "__main__":
    unittest.main()
