"""
Code generator for creating Python scripts to numerically evaluate mathematical expressions
and generate plots.
"""

import sympy as sp
import numpy as np
from typing import List, Dict, Any, Optional
import json
import os
from datetime import datetime


class CodeGenerator:
    """Generates Python code for numerical evaluation and plotting of mathematical expressions."""

    def __init__(self, output_dir: str = "./output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "plots"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "data"), exist_ok=True)

    def generate_evaluation_code(self, tasks: List[Dict[str, Any]]) -> str:
        """
        Generate complete Python code for evaluating expressions and generating plots.

        Args:
            tasks: List of computation tasks from analyzer

        Returns:
            Complete Python code as string
        """
        code_parts = [
            self._generate_header(),
            self._generate_imports(),
            self._generate_helper_functions(),
        ]

        # Generate code for each task
        for i, task in enumerate(tasks):
            code_parts.append(
                f'\n# Task {i+1}: {task["goal_type"].title()} of {task["expression"]}'
            )
            code_parts.append(
                self._generate_task_code(task, i+1)
            )

        code_parts.extend([
            self._generate_main_execution(),
            self._generate_footer()
        ])

        return '\n'.join(code_parts)

    def _generate_header(self) -> str:
        """Generate file header with metadata."""
        return f'''"""
Generated by ParSub - Agentic Math/Physics Research Tool
Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

'''

    def _generate_imports(self) -> str:
        """Generate import statements."""
        return '''import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import pandas as pd
import json
import os
from mpl_toolkits.mplot3d import Axes3D
from typing import Dict, List, Tuple, Any
import warnings
warnings.filterwarnings('ignore')

# Set up matplotlib for high-resolution output
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['font.size'] = 10
'''

    def _generate_helper_functions(self) -> str:
        """Generate helper functions for common operations."""
        return '''
def lambdify_expr(expr, variables):
    """Convert SymPy expression to NumPy-compatible function."""
    return sp.lambdify(variables, expr, modules=['numpy', {'Heaviside': lambda x: np.heaviside(x, 0.5)}])

def evaluate_expression(expr, variables, values_dict):
    """Evaluate expression with given variable values."""
    subs_dict = {var: values_dict[var] for var in variables if var in values_dict}
    result = expr.subs(subs_dict)
    if result.is_number:
        return float(result.evalf())
    return result

def save_plot(fig, filename, output_dir="./output/plots"):
    """Save plot with high resolution."""
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)
    fig.savefig(filepath, dpi=300, bbox_inches='tight')
    plt.close(fig)
    return filepath

def save_data(data, filename, output_dir="./output/data"):
    """Save data as CSV/TSV/Excel."""
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)

    if isinstance(data, dict):
        df = pd.DataFrame(data)
    elif isinstance(data, np.ndarray):
        df = pd.DataFrame(data)
    else:
        df = pd.DataFrame([data])

    if filename.endswith('.csv'):
        df.to_csv(filepath, index=False)
    elif filename.endswith('.tsv'):
        df.to_csv(filepath, sep='\\t', index=False)
    elif filename.endswith('.xlsx') or filename.endswith('.xls'):
        df.to_excel(filepath, index=False)
    else:
        # Default to CSV
        df.to_csv(filepath + '.csv', index=False)
        filepath = filepath + '.csv'

    return filepath

def create_parameter_grid(param_ranges, points=50):
    """Create parameter grid for sampling."""
    grids = []
    for param, (low, high) in param_ranges.items():
        grids.append(np.linspace(low, high, points))
    return np.meshgrid(*grids) if len(grids) > 1 else grids[0]
'''

    def _generate_task_code(self, task: Dict[str, Any], task_num: int) -> str:
        """Generate code for a specific task."""
        goal_type = task['goal_type']
        expression = task['expression']
        variables = task['variables']
        sampling = task['suggested_sampling']

        if goal_type == 'evaluate':
            return self._generate_evaluation_code_block(expression, variables, sampling, task_num)
        elif goal_type == 'plot':
            return self._generate_plot_code_block(expression, variables, sampling, task_num)
        elif goal_type == 'solve':
            return self._generate_solve_code_block(expression, variables, sampling, task_num)
        elif goal_type == 'optimize':
            return self._generate_optimize_code_block(expression, variables, sampling, task_num)
        elif goal_type == 'integrate':
            return self._generate_integrate_code_block(expression, variables, sampling, task_num)
        elif goal_type == 'differentiate':
            return self._generate_differentiate_code_block(expression, variables, sampling, task_num)
        else:
            # Default to evaluation
            return self._generate_evaluation_code_block(expression, variables, sampling, task_num)

    def _generate_evaluation_code_block(self, expression: str, variables: List[str],
                                      sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for expression evaluation."""
        var_str = ', '.join(variables) if variables else ''
        var_list = f'[{var_str}]' if variables else '[]'

        code = f'''
# Task {task_num}: Evaluate expression
expr_{task_num} = sp.sympify("{expression}")
if {variables}:
    f_{task_num} = lambdify_expr(expr_{task_num}, [{var_str}])

    # Generate parameter samples
    param_values_{task_num} = {{}}
    '''
        for var, (low, high) in sampling['ranges'].items():
            code += f"    param_values_{task_num}['{var}'] = np.linspace({low}, {high}, {sampling['points']})\\n"

        code += f'''
    # Create parameter combinations
    if len({variables}) == 1:
        # Single variable case
        samples_{task_num} = np.array([[{var}, f_{task_num}({var})]
                                     for {var} in param_values_{task_num}['{variables[0]}']])
        results_{task_num} = samples_{task_num}[:, 1]

        # Save results
        save_data({{
            'variable': samples_{task_num}[:, 0],
            'value': results_{task_num}
        }}, f"task_{task_num}_evaluation.csv")
    else:
        # Multi-variable case - evaluate at center points or create grid
        center_point_{task_num} = {{}}
        for var in {variables}:
            low, high = sampling['ranges'][var]
            center_point_{task_num}[var] = (low + high) / 2

        result_{task_num} = evaluate_expression(expr_{task_num}, {variables}, center_point_{task_num})
        save_data({{
            'expression': "{expression}",
            'result': result_{task_num},
            'evaluation_point': str(center_point_{task_num})
        }}, f"task_{task_num}_evaluation.json")
else:
    # No variables - direct evaluation
    result_{task_num} = float(expr_{task_num}.evalf())
    save_data({{
        'expression': "{expression}",
        'result': result_{task_num}
    }}, f"task_{task_num}_evaluation.json")
'''
        return code

    def _generate_plot_code_block(self, expression: str, variables: List[str],
                                  sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for plotting."""
        if len(variables) == 1:
            return self._generate_1d_plot_code(expression, variables[0], sampling, task_num)
        elif len(variables) == 2:
            return self._generate_2d_plot_code(expression, variables[0], variables[1], sampling, task_num)
        else:
            # For 3+ variables, plot first two or create slices
            return self._generate_1d_plot_code(expression, variables[0], sampling, task_num) + \
                   f"\n# Note: For {len(variables)} variables, showing plot for first variable '{variables[0]}'"

    def _generate_1d_plot_code(self, expression: str, var: str,
                               sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for 1D plotting."""
        low, high = sampling['ranges'][var]
        points = sampling['points']

        code = f'''
# Task {task_num}: 1D Plot
x_{task_num} = np.linspace({low}, {high}, {points})
expr_{task_num} = sp.sympify("{expression}")
f_{task_num} = lambdify_expr(expr_{task_num}, ['{var}'])
y_{task_num} = f_{task_num}(x_{task_num})

# Create plot
fig_{task_num}, ax_{task_num} = plt.subplots(figsize=(10, 6))
ax_{task_num}.plot(x_{task_num}, y_{task_num}, 'b-', linewidth=2)
ax_{task_num}.set_xlabel('{var}')
ax_{task_num}.set_ylabel('f({var})')
ax_{task_num}.set_title('Plot of {expression}')
ax_{task_num}.grid(True, alpha=0.3)

# Save plot
save_plot(fig_{task_num}, f"task_{task_num}_plot.png")

# Save data
save_data({{
    '{var}': x_{task_num},
    'f({var})': y_{task_num}
}}, f"task_{task_num}_plot_data.csv")
'''
        return code

    def _generate_2d_plot_code(self, expression: str, var1: str, var2: str,
                               sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for 2D plotting (surface plot)."""
        low1, high1 = sampling['ranges'][var1]
        low2, high2 = sampling['ranges'][var2]
        points = int(np.sqrt(sampling['points']))  # Adjust for 2D grid

        code = f'''
# Task {task_num}: 2D Surface Plot
x1_{task_num} = np.linspace({low1}, {high1}, {points})
x2_{task_num} = np.linspace({low2}, {high2}, {points})
X1_{task_num}, X2_{task_num} = np.meshgrid(x1_{task_num}, x2_{task_num})
expr_{task_num} = sp.sympify("{expression}")
f_{task_num} = lambdify_expr(expr_{task_num}, ['{var1}', '{var2}'])
Y_{task_num} = f_{task_num}(X1_{task_num}, X2_{task_num})

# Create surface plot
fig_{task_num} = plt.figure(figsize=(12, 9))
ax_{task_num} = fig_{task_num}.add_subplot(111, projection='3d')
surf = ax_{task_num}.plot_surface(X1_{task_num}, X2_{task_num}, Y_{task_num},
                                  cmap='viridis', alpha=0.9)
ax_{task_num}.set_xlabel('{var1}')
ax_{task_num}.set_ylabel('{var2}')
ax_{task_num}.set_zlabel('f({var1},{var2})')
ax_{task_num}.set_title('Surface Plot of {expression}')

# Add colorbar
fig_{task_num}.colorbar(surf, shrink=0.5, aspect=5)

# Save plot
save_plot(fig_{task_num}, f"task_{task_num}_surface_plot.png")

# Save data (flattened for CSV)
save_data({{
    f'{var1}': X1_{task_num}.flatten(),
    f'{var2}': X2_{task_num}.flatten(),
    'f': Y_{task_num}.flatten()
}}, f"task_{task_num}_surface_data.csv")
'''
        return code

    def _generate_solve_code_block(self, expression: str, variables: List[str],
                                   sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for solving equations."""
        # Assuming expression is an equation like "expr = 0" or we need to solve expr = 0
        var_str = ', '.join(variables) if variables else ''

        code = f'''
# Task {task_num}: Solve equation
expr_{task_num} = sp.sympify("{expression}")
'''
        if variables:
            code += f'''
# Solve for variables: {var_str}
solutions_{task_num} = sp.solve(expr_{task_num}, [{var_str}])
'''
        else:
            code += f'''
# Solve equation (no variables to solve for)
solutions_{task_num} = sp.solve(expr_{task_num})
'''

        code += f'''
# Save solutions
save_data({{
    'expression': "{expression}",
    'solutions': [str(sol) for sol in solutions_{task_num}] if isinstance(solutions_{task_num}, list) else str(solutions_{task_num}),
    'num_solutions': len(solutions_{task_num}) if isinstance(solutions_{task_num}, list) else 1
}}, f"task_{task_num}_solutions.json")

# If we have variables and solutions are numeric, also plot
if {variables} and solutions_{task_num}:
    try:
        # Try to get numeric solutions for plotting
        numeric_sols = []
        for sol in solutions_{task_num} if isinstance(solutions_{task_num}, list) else [solutions_{task_num}]:
            if sol.is_number:
                numeric_sols.append(float(sol.evalf()))

        if numeric_sols and len({variables}) == 1:
            var = {variables[0]}
            # Plot the function and mark solutions
            x_vals = np.linspace({sampling['ranges'].get(var, (-5, 5))[0]},
                               {sampling['ranges'].get(var, (-5, 5))[1]}, 200)
            expr = sp.sympify("{expression}")
            f = lambdify_expr(expr, ['{var}'])
            y_vals = f(x_vals)

            fig, ax = plt.subplots(figsize=(10, 6))
            ax.plot(x_vals, y_vals, 'b-', linewidth=2, label='f({var})')
            ax.axhline(y=0, color='k', linestyle='-', alpha=0.3)
            for sol in numeric_sols:
                ax.axvline(x=sol, color='red', linestyle='--', alpha=0.7, label=f'Solution: {{sol:.3f}}')
            ax.set_xlabel('{var}')
            ax.set_ylabel('f({var})')
            ax.set_title('Function and Solutions')
            ax.legend()
            ax.grid(True, alpha=0.3)
            save_plot(fig, f"task_{task_num}_solutions_plot.png")
    except Exception as e:
        pass  # Skip plotting if there are issues
'''
        return code

    def _generate_optimize_code_block(self, expression: str, variables: List[str],
                                      sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for optimization."""
        from scipy import optimize

        var_str = ', '.join(variables) if variables else ''
        bounds_str = ', '.join([f"({sampling['ranges'].get(var, (-5, 5))[0]}, {sampling['ranges'].get(var, (-5, 5))[1]})"
                               for var in variables]) if variables else ''

        code = f'''
# Task {task_num}: Optimization
expr_{task_num} = sp.sympify("{expression}")
f_{task_num} = lambdify_expr(expr_{task_num}, [{var_str}]) if {variables} else lambda: float(expr_{task_num}.evalf())
'''
        if variables:
            code += f'''
# Define objective function (negative for maximization if needed)
def objective_{task_num}(params):
    return f_{task_num}(*params)

# Set bounds
bounds_{task_num} = [{bounds_str}] if {variables} else []

# Perform optimization
result_{task_num} = optimize.minimize(objective_{task_num},
                                    x0=[np.mean([b[0], b[1]]) for b in bounds_{task_num}] if bounds_{task_num} else [0],
                                    bounds=bounds_{task_num} if bounds_{task_num} else None)

# Save results
save_data({{
    'expression': "{expression}",
    'optimization_type': 'minimization',
    'optimal_point': result_{task_num}.x.tolist() if hasattr(result_{task_num}, 'x') else [],
    'optimal_value': float(result_{task_num}.fun),
    'success': result_{task_num}.success,
    'message': result_{task_num}.message
}}, f"task_{task_num}_optimization.json")
'''
        else:
            code += f'''
# No variables to optimize - just evaluate
result_{task_num} = f_{task_num}()
save_data({{
    'expression': "{expression}",
    'value': result_{task_num}
}}, f"task_{task_num}_optimization.json")
'''
        return code

    def _generate_integrate_code_block(self, expression: str, variables: List[str],
                                       sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for integration."""
        code = f'''
# Task {task_num}: Integration
expr_{task_num} = sp.sympify("{expression}")
'''
        if variables:
            # Multiple integrals
            integrals = []
            limits_str = []
            for var in variables:
                low, high = sampling['ranges'].get(var, (-5, 5))
                integrals.append(var)
                limits_str.append(f"({var}, {low}, {high})")

            code += f'''
# Perform {len(variables)}-dimensional integration
integral_{task_num} = sp.integrate(expr_{task_num}, {', '.join(limits_str)})

# Save results
save_data({{
    'expression': "{expression}",
    'integral': str(integral_{task_num}),
    'integral_value': float(integral_{task_num}.evalf()) if integral_{task_num}.is_number else None,
    'variables_of_integration': {variables}
}}, f"task_{task_num}_integration.json")
'''
        else:
            code += f'''
# Indefinite integral (no variables specified)
integral_{task_num} = sp.integrate(expr_{task_num})

# Save results
save_data({{
    'expression': "{expression}",
    'indefinite_integral': str(integral_{task_num})
}}, f"task_{task_num}_integration.json")
'''
        return code

    def _generate_differentiate_code_block(self, expression: str, variables: List[str],
                                           sampling: Dict[str, Any], task_num: int) -> str:
        """Generate code for differentiation."""
        code = f'''
# Task {task_num}: Differentiation
expr_{task_num} = sp.sympify("{expression}")
'''
        if variables:
            # Partial derivatives
            derivatives = []
            for var in variables:
                derivatives.append(var)

            code += f'''
# Compute partial derivatives
'''
            for var in derivatives:
                code += f'''deriv_{task_num}_{var} = sp.diff(expr_{task_num}, '{var}')
'''

            code += f'''
# Save results
derivatives_dict = {{}}
'''
            for var in derivatives:
                code += f"derivatives_dict['{var}'] = str(deriv_{task_num}_{var})\\n"

            code += f'''
save_data({{
    'expression': "{expression}",
    'partial_derivatives': derivatives_dict
}}, f"task_{task_num}_differentiation.json")
'''
        else:
            code += f'''
# Derivative with respect to default variable (assume x if present, else first variable)
deriv_var = 'x' if 'x' in str(expr_{task_num}.free_symbols) else (list(expr_{task_num}.free_symbols)[0] if expr_{task_num}.free_symbols else None)
if deriv_var:
    deriv_{task_num} = sp.diff(expr_{task_num}, deriv_var)
    save_data({{
        'expression': "{expression}",
        'variable_of_differentiation': deriv_var,
        'derivative': str(deriv_{task_num})
    }}, f"task_{task_num}_differentiation.json")
else:
    # No variables - derivative is zero
    save_data({{
        'expression': "{expression}",
        'derivative': "0"
    }}, f"task_{task_num}_differentiation.json")
'''
        return code

    def _generate_main_execution(self) -> str:
        """Generate main execution block."""
        return '''
if __name__ == "__main__":
    print("ParSub Mathematical Computation Suite")
    print("=" * 50)
    print("All tasks completed. Output saved to ./output/")
    print("- Plots saved to ./output/plots/")
    print("- Data saved to ./output/data/")
'''

    def _generate_footer(self) -> str:
        """Generate file footer."""
        return '''
print("Generation completed successfully!")
'''

    def save_code(self, code: str, filename: str = "generated_computation.py") -> str:
        """Save generated code to file."""
        os.makedirs(self.output_dir, exist_ok=True)
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(code)
        return filepath


# Convenience function
def generate_code_from_tasks(tasks: List[Dict[str, Any]],
                           output_dir: str = "./output") -> str:
    """Generate Python code from computation tasks."""
    generator = CodeGenerator(output_dir)
    code = generator.generate_evaluation_code(tasks)
    filepath = generator.save_code(code)
    return filepath