"""
Code generator for creating Python scripts that numerically evaluate
mathematical expressions and generate plots and data files.

A generated script is self-contained: it embeds the helper library from
:mod:`parsub.generator.runtime` followed by one small function per task, so it
can be inspected, edited (ranges, fixed parameter values, ...) and re-run
without ParSub being installed.
"""

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from parsub import __version__
from parsub.generator import runtime as _runtime

GENERATED_FILENAME = "generated_computation.py"


def _runtime_source() -> str:
    """Source of the runtime module without its module docstring."""
    source = Path(_runtime.__file__).read_text(encoding="utf-8")
    match = re.match(r'\s*"""(?:.|\n)*?"""\s*\n', source)
    return source[match.end():] if match else source


def _comment(text: str, limit: int = 300) -> str:
    """Make arbitrary text safe for a single-line comment or a docstring line."""
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    text = text.replace("\\", "/").replace('"', "'")
    return text if len(text) <= limit else text[: limit - 3] + "..."


def _float_dict(values: Dict[str, Any]) -> Dict[str, float]:
    return {str(k): float(v) for k, v in (values or {}).items()}


def _range_dict(ranges: Dict[str, Any]) -> Dict[str, tuple]:
    return {str(k): (float(v[0]), float(v[1])) for k, v in (ranges or {}).items()}


class CodeGenerator:
    """Generates Python code for numerical evaluation and plotting of mathematical expressions."""

    def __init__(self, output_dir: str = "./output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "plots"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "data"), exist_ok=True)

    # ------------------------------------------------------------------ public
    def generate_evaluation_code(self, tasks: List[Dict[str, Any]], source_name: Optional[str] = None) -> str:
        """
        Generate complete Python code for evaluating expressions and generating plots.

        Args:
            tasks: List of computation tasks from the analyzer
            source_name: Optional name of the LaTeX source (for the header)

        Returns:
            Complete Python code as a string
        """
        code_parts = [
            self._generate_header(source_name, len(tasks)),
            self._generate_imports(),
            self._generate_helper_functions(),
        ]
        for i, task in enumerate(tasks):
            code_parts.append(self._generate_task_code(task, i + 1))
        code_parts.append(self._generate_task_table(tasks))
        code_parts.append(self._generate_main_execution())
        return "\n".join(code_parts)

    def save_code(self, code: str, filename: str = GENERATED_FILENAME) -> str:
        """Save generated code to a file in the output directory and return its path."""
        os.makedirs(self.output_dir, exist_ok=True)
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as handle:
            handle.write(code)
        return filepath

    # --------------------------------------------------------------- sections
    def _generate_header(self, source_name: Optional[str] = None, task_count: int = 0) -> str:
        """Generate the module docstring of the generated file."""
        source = f"Source: {_comment(source_name, 200)}\n" if source_name else ""
        return f'''"""Generated by ParSub {__version__} - Agentic Math/Physics Research Tool.

{source}Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Tasks: {task_count}

Run:
    python {GENERATED_FILENAME} [--output-dir DIR] [--timeout SECONDS] [--tasks 1,2]

Plots are written to <output>/plots and data to <output>/data, where <output>
defaults to the directory containing this script (or $PARSUB_OUTPUT_DIR).
Every task is a small function at the end of this file: edit the ranges or the
fixed parameter values there and re-run the script.
"""
'''

    def _generate_imports(self) -> str:
        """Import statements and plotting configuration (part of the runtime)."""
        return "# " + "=" * 76 + "\n# ParSub runtime helpers (inlined from parsub.generator.runtime)\n# " + "=" * 76

    def _generate_helper_functions(self) -> str:
        """Helper library used by the task functions (lambdify_expr, save_plot, save_data, ...)."""
        return _runtime_source()

    def _generate_task_code(self, task: Dict[str, Any], task_num: int) -> str:
        """Generate the function that performs one task."""
        goal = task.get("goal_type", "evaluate")
        expression_text = task.get("srepr") or task.get("expression", "0")
        independent = list(task.get("independent_variables") or [])
        variables = list(task.get("variables") or [])
        sampling = task.get("suggested_sampling") or {}
        ranges = _range_dict(sampling.get("ranges") or {})
        points = int(sampling.get("points") or 100)
        fixed = _float_dict(task.get("fixed_parameters") or {})
        options = task.get("options") or {}
        label = task.get("label") or "f"

        if not independent and variables and goal != "symbolic" and not task.get("fixed_parameters"):
            # Older task dictionaries (without variable roles): sweep the first variable(s)
            independent = variables[:2] if goal == "plot" else variables[:1]
            fixed = {}
        for var in variables:
            ranges.setdefault(var, (-5.0, 5.0))

        title = task.get("description") or f"{goal} {task.get('expression', '')}"
        lines = [
            "",
            "# " + "-" * 76,
            f"# Task {task_num}: {_comment(title, 150)}",
        ]
        if task.get("source_latex"):
            source_ref = f" (equation {task['source_label']})" if task.get("source_label") else ""
            lines.append("# " + _comment(f"LaTeX{source_ref}: {task['source_latex']}", 220))
        lines += ["# " + "-" * 76, f"def task_{task_num}(ctx):", f'    """{_comment(title, 150)}"""']

        common = f"fixed={fixed!r},\n        ranges={ranges!r}"
        equation = task.get("equation") or {}
        if goal in ("solve", "verify"):
            lhs = equation.get("lhs") or expression_text
            rhs = equation.get("rhs") or "Integer(0)"
            lines.append(f"    lhs = parse_sympy({lhs!r})")
            lines.append(f"    rhs = parse_sympy({rhs!r})")
        else:
            lines.append(f"    expr = parse_sympy({expression_text!r})")

        if goal == "plot":
            call = (f"plot_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        points={points}, label={label!r},\n    )")
        elif goal == "solve":
            solve_for = options.get("solve_for") or (independent[0] if independent else None)
            call = (f"solve_task(\n        ctx, {task_num}, lhs, rhs, solve_for={solve_for!r},\n        {common},\n"
                    f"        points={points},\n    )")
        elif goal == "verify":
            call = (f"verify_task(\n        ctx, {task_num}, lhs, rhs, independent={independent!r},\n        {common},\n"
                    f"        points={points},\n    )")
        elif goal == "optimize":
            direction = options.get("direction", "both")
            call = (f"optimize_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        direction={direction!r}, points={points},\n    )")
        elif goal == "integrate":
            call = (f"integrate_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        points={points},\n    )")
        elif goal == "differentiate":
            call = (f"differentiate_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        points={points},\n    )")
        elif goal == "series":
            call = (f"series_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        order={int(options.get('order', 6))}, point={options.get('point', 0)!r}, points={points},\n    )")
        elif goal == "symbolic":
            call = f"symbolic_task(ctx, {task_num}, expr)"
        else:  # evaluate (and any unknown goal)
            parameters = task.get("parameters") or {}
            point = {
                var: float(parameters[var]["default"])
                for var in independent
                if isinstance(parameters.get(var), dict) and parameters[var].get("default") is not None
            }
            call = (f"evaluate_task(\n        ctx, {task_num}, expr, independent={independent!r},\n        {common},\n"
                    f"        points={points}, label={label!r}, point={point!r},\n    )")
        lines.append(f"    return {call}")
        return "\n".join(lines) + "\n"

    def _generate_task_table(self, tasks: List[Dict[str, Any]]) -> str:
        """The list of tasks executed by ``run_tasks``."""
        rows = []
        for i, task in enumerate(tasks):
            description = _comment(task.get("description") or task.get("expression", ""), 200)
            rows.append(f"    ({i + 1}, {task.get('goal_type', 'evaluate')!r}, {description!r}, task_{i + 1}),")
        body = "\n".join(rows)
        return f"\nTASKS = [\n{body}\n]\n" if rows else "\nTASKS = []\n"

    def _generate_main_execution(self) -> str:
        """Generate the main execution block."""
        return '''
if __name__ == "__main__":
    sys.exit(run_tasks(TASKS, default_output_dir=os.path.dirname(os.path.abspath(__file__))))
'''


# Convenience function
def generate_code_from_tasks(tasks: List[Dict[str, Any]], output_dir: str = "./output",
                             source_name: Optional[str] = None) -> str:
    """Generate Python code from computation tasks, save it and return its path."""
    generator = CodeGenerator(output_dir)
    code = generator.generate_evaluation_code(tasks, source_name=source_name)
    return generator.save_code(code)
